name: build images

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
          qemu-version: latest
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Run Buildx
        run: |
          echo $
          docker buildx create --use --name build --node build --driver-opt network=host
          docker buildx build \
            --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 \
            --output "type=image,push=true" \
            --tag osminogin/tor-simple \
            --build-arg VERSION=$(head -1 VERSION) \
            --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            --build-arg VCS_REF=${GITHUB_SHA::8} \
            .
