name: Latest version

on:
  schedule:
    - cron:  "30 2 * * *"

jobs:

  check:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Get remote package data
        uses: wei/curl@master
        with:
          args: --silent "https://pkgs.alpinelinux.org/package/edge/community/x86_64/tor" --output ./package_data.html

      - name: Cut version from package data
        run: |
          echo ::debug::Curl version `curl --version`
          grep -A 3 -i version | sed -E 's#.*>([0-9r.-]+)</a>#\1#g' | tail -1 > ./latest_version.txt

      - name: Print remote version
        run: |
          echo ::debug::Tor remote package version ` cat ./latest_version.txt`

      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: latest-version
      #     path: ./latest_version.txt

      - name: Check remote version with local
        run: |
          grep -q `cat ./latest_version.txt` VERSION
